# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Base = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Base.sizePolicy().hasHeightForWidth())
        self.Base.setSizePolicy(sizePolicy)
        self.Base.setObjectName("Base")
        self.horizontalLayout.addWidget(self.Base)
        self.Quote = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Quote.sizePolicy().hasHeightForWidth())
        self.Quote.setSizePolicy(sizePolicy)
        self.Quote.setObjectName("Quote")
        self.horizontalLayout.addWidget(self.Quote)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.UnsubscribeDepth = QtWidgets.QPushButton(self.centralwidget)
        self.UnsubscribeDepth.setObjectName("UnsubscribeDepth")
        self.gridLayout.addWidget(self.UnsubscribeDepth, 1, 1, 1, 1)
        self.UnsubscribeTop = QtWidgets.QPushButton(self.centralwidget)
        self.UnsubscribeTop.setObjectName("UnsubscribeTop")
        self.gridLayout.addWidget(self.UnsubscribeTop, 1, 0, 1, 1)
        self.SubscribeTop = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubscribeTop.sizePolicy().hasHeightForWidth())
        self.SubscribeTop.setSizePolicy(sizePolicy)
        self.SubscribeTop.setMinimumSize(QtCore.QSize(145, 0))
        self.SubscribeTop.setObjectName("SubscribeTop")
        self.gridLayout.addWidget(self.SubscribeTop, 0, 0, 1, 1)
        self.SubscribeDepth = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubscribeDepth.sizePolicy().hasHeightForWidth())
        self.SubscribeDepth.setSizePolicy(sizePolicy)
        self.SubscribeDepth.setMinimumSize(QtCore.QSize(145, 0))
        self.SubscribeDepth.setObjectName("SubscribeDepth")
        self.gridLayout.addWidget(self.SubscribeDepth, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.LoggerBox = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.LoggerBox.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.LoggerBox.setObjectName("LoggerBox")
        self.verticalLayout.addWidget(self.LoggerBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.UnsubscribeDepth.setText(_translate("MainWindow", "Unsubscribe Depth"))
        self.UnsubscribeTop.setText(_translate("MainWindow", "Unsubscribe Top"))
        self.SubscribeTop.setText(_translate("MainWindow", "Subscribe Top"))
        self.SubscribeDepth.setText(_translate("MainWindow", "Subscribe Depth"))
